# Task Name: (Required)
task_name: 'task name'
# Task Author: (Required)
author: 'Koii'
# Task Description: (Required)
description: 'description'
# Repository URL: (Required)
repositoryUrl: 'https://github.com/koii-network/task-template'
# Image URL: (Required) Will be displayed in desktop node
imageUrl: 'imageUrl'
# Info URL: (Required) Will be displayed in desktop node
infoUrl: 'infoUrl'

# Task executable network: (Required | DEVELOPMENT, ARWEAVE, or IPFS) : IPFS is the default and common value
task_executable_network: 'IPFS'

# Task audit program: (Required) IPFS: Path to your executable | DEVELOPMENT: Leave it as 'main'
task_audit_program: 'dist/main.js'

# Round time: (Required) Duration of task, measured in slots (with each slot approximately equal to 408ms).
round_time: 1500

## Audit Window ##
# The audit window should be at least 1/3 of the round time.
audit_window: 350

## Submission Window ##
# The submission window should be at least 1/3 of the round time.
submission_window: 350

## Minimum Stake Amount ##
# The minimum amount of KOII that a user must stake in order to participate in the task.
minimum_stake_amount: 0.1

## Task Bounty Type ##
# KOII or KPL
task_type: "KPL"

## Token Mint Address (ONLY for KPL tasks) ##
# The Fire Token address is provided as an example.
token_type: "BAmB86Mt6FDaqTjLzKimBjHtwV93PGQitjW5zKNnBVEU"

## Total Bounty Amount ##
# The total bounty amount that will be available for distribution over all rounds.
# Does nothing when updating a task.
total_bounty_amount: 10

## Bounty Amount per Round ##
# The maximum amount that can be distributed per round.
# If the actual distribution per round exceeds this amount, the distribution list will fail.
bounty_amount_per_round: 0.1

## Allowed Failed Distributions ##
# Number of retries allowed for the distribution list if it is fails audit.
# If all retries fail, the task will not distribute anything for the round.
# This is also the number of rounds of submissions it will keep.
allowed_failed_distributions: 3

## Space ##
# Expected Task Data Size in MBs for the account size.
# Minimums: 2 for whitelisted tasks, 1 for production, 0.1 for testing
# Calculation Details: https://www.koii.network/docs/develop/command-line-tool/create-task-cli/create-task#space
space: 0.1

## Requirement Tags (Optional) ##
# To add more global variables and task variables, please refer to the type, value, description format shown below.
requirementsTags:
  - type: CPU
    value: "4-core"
  - type: RAM
    value: "5 GB"
  - type: STORAGE
    value: "5 GB"
  - type: TASK_VARIABLE
    value: 'TWITTER_PASSWORD'
    description: 'The password of your volunteer Twitter account.'

# Tags: You can select the tags here via https://www.koii.network/docs/develop/command-line-tool/create-task-cli/create-task#tags
tags: ["AI", "ML"]
# Environment: (Required | TEST or PRODUCTION) Production mode will expose your task to all the task runners.
environment: "TEST"

#################################### FOR UPDATING TASKS ONLY ####################################

## Old Task ID ##
task_id: ""

## Migration Description ##
migrationDescription: ""
